[package]
name = "elsa"
version = "0.1.0"
edition = "2021"
authors = ["Divy Srivastava <dj.srivastava23@gmail.com>"]

[features]
use_v8 = ["v8"]
use_quickjs = ["quickjs-ng-sys"]
use_jsc = ["rusty_jsc_sys"]
use_spidermonkey = ["mozjs"]
# use_hermes = ["libhermesabi-sys"]

typescript = ["swc_common", "swc_ecma_codegen", "swc_ecma_parser", "swc_ecma_transforms_base", "swc_ecma_visit", "swc_ecma_transforms_typescript"]

default = ["use_v8"]

[[bin]]
name = "elsa"
path = "main.rs"

[dependencies]
# engines
v8 = { version = "0.81.0", optional = true }
rusty_jsc_sys = { version = "0.0.3", optional = true }
mozjs = { git = "https://github.com/servo/mozjs", rev = "0623d5fced66007ec7a35d1ca9a3cfd1b30f27f9", optional = true }
# libquickjs-sys = { version = "0.10.0", optional = true }
quickjs-ng-sys = { git = "https://github.com/elsaland/quickjs-ng-rs", optional = true }
# libhermesabi-sys = { path = "../libhermesabi-sys", optional = true }

# esm and typescript
swc_common = { version = "0.29.15", features = ["tty-emitter"], optional = true }
swc_ecma_codegen = { version = "0.127.36", optional = true  }
swc_ecma_parser = { version = "0.122.29", optional = true  }
swc_ecma_transforms_base = { version = "0.111.59", optional = true }
swc_ecma_visit = { version = "0.80.20", optional = true }
swc_ecma_transforms_typescript = { version = "0.159.22", optional = true }

libc = "0.2.150"

# io
# liburing = { path = "../uring-sys" }
liburing = { git = "https://github.com/littledivy/uring-sys" }

[profile.release]
lto = true
strip = "symbols"

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"

[profile.dev.build-override]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
